# name: Deploy to Truehost for mayowaojo.com via FTP

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Install and Build
#         run: |
#           npm install
#           npm run build

#       - name: FTP Deploy
#         uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#         with:
#           server: ${{ secrets.FTP_SERVER }}
#           username: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           port: ${{ secrets.FTP_PORT }}
#           local-dir: ./dist/
#           server-dir: /public_html/
# 
name: Deploy to Truehost for mayowaojo.com  via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          source: "dist/*"
          target: "/home/${{ secrets.FTP_USERNAME }}/public_html/"